eureka:
  client:
    register-with-eureka: true #启用自己作为客户端注册，禁用的话spring boot admin就看不到eureka-server的服务了，也就无法检测状态了
    fetch-registry: true #是否需要去检索寻找服务,因为是注册中心，他的任务是维护服务实例，所以不需要去寻找服务，默认是true
    # 服务清单的缓存更新时间，默认30秒一次
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://192.168.81.31:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间，10秒，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    ip-address: 127.0.0.1
logging:
  file: "/home/mect/log/${spring.application.name}/${spring.application.name}.log"
spring:
  boot:
    admin:
      client:
        url: "http://192.168.81.31:5000"
