version: '3'
services:
  jenkins-deploy:
    image: java:8
    restart: always
    container_name: mect-jenkins-deploy
    environment:
    - TZ=Asia/Shanghai
    network_mode: host
    ports:
    - 7777:7777
    volumes:
    - /root:/root:rw
    - /tmp
    command: java -Djava.security.egd=file:/dev/./urandom -jar /root/jenkins/jenkins-deploy-0.0.1-SNAPSHOT.jar
